# Generated by Django 5.2.6 on 2025-09-18 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_book_id', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(blank=True, max_length=255, null=True)),
                ('total_pages', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reading', '읽는 중'), ('completed', '완독'), ('paused', '일시정지'), ('dropped', '중단')], default='reading', max_length=20)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='books_userb_user_id_ceb945_idx')],
            },
        ),
    ]
