# Generated by Django 5.2.6 on 2025-09-18 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('note_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.userbook')),
            ],
            options={
                'indexes': [models.Index(fields=['user_book'], name='reading_rea_user_bo_729f7c_idx'), models.Index(fields=['page_number'], name='reading_rea_page_nu_c17012_idx')],
            },
        ),
    ]
