# Generated by Django 5.2.6 on 2025-09-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')])),
                ('liked_point', models.TextField(blank=True, null=True)),
                ('disliked_point', models.TextField(blank=True, null=True)),
                ('review_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='books.userbook')),
            ],
            options={
                'indexes': [models.Index(fields=['user_book'], name='reading_boo_user_bo_1c0022_idx')],
            },
        ),
    ]
